insert into tbl_user (id, email, created_on, updated_on) values (1, 'test1@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (2, 'test2@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (3, 'test3@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (4, 'test4@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (5, 'test5@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (6, 'test6@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (7, 'test7@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (8, 'test8@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (9, 'test9@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (10, 'test10@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (11, 'test11@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (12, 'test12@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (13, 'test13@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (14, 'test14@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (15, 'test15@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (16, 'test16@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (17, 'test17@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (18, 'test18@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (19, 'test19@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (20, 'test20@test.com',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());

insert into tbl_user_friends (user_id, friend_id) values (1,2);
insert into tbl_user_friends (user_id, friend_id) values (1,3);
insert into tbl_user_friends (user_id, friend_id) values (1,4);
insert into tbl_user_friends (user_id, friend_id) values (1,5);
insert into tbl_user_friends (user_id, friend_id) values (1,6);
insert into tbl_user_friends (user_id, friend_id) values (1,7);
insert into tbl_user_friends (user_id, friend_id) values (1,8);
insert into tbl_user_friends (user_id, friend_id) values (2,1);
insert into tbl_user_friends (user_id, friend_id) values (2,3);
insert into tbl_user_friends (user_id, friend_id) values (2,4);
insert into tbl_user_friends (user_id, friend_id) values (2,5);
insert into tbl_user_friends (user_id, friend_id) values (2,6);
insert into tbl_user_friends (user_id, friend_id) values (2,7);
insert into tbl_user_friends (user_id, friend_id) values (2,8);
insert into tbl_user_friends (user_id, friend_id) values (3,1);
insert into tbl_user_friends (user_id, friend_id) values (3,2);
insert into tbl_user_friends (user_id, friend_id) values (4,1);
insert into tbl_user_friends (user_id, friend_id) values (4,2);
insert into tbl_user_friends (user_id, friend_id) values (5,1);
insert into tbl_user_friends (user_id, friend_id) values (5,2);
insert into tbl_user_friends (user_id, friend_id) values (6,1);
insert into tbl_user_friends (user_id, friend_id) values (6,2);
insert into tbl_user_friends (user_id, friend_id) values (7,1);
insert into tbl_user_friends (user_id, friend_id) values (7,2);
insert into tbl_user_friends (user_id, friend_id) values (8,1);
insert into tbl_user_friends (user_id, friend_id) values (8,2);
