insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test1@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test2@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test3@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test4@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test5@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test6@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test7@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test8@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test9@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test10@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test11@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test12@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test13@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test14@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test15@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test16@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test17@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test18@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test19@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user (id, email, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 'test20@test.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into tbl_user_friends (user_id, friend_id) values (1,2);
insert into tbl_user_friends (user_id, friend_id) values (1,3);
insert into tbl_user_friends (user_id, friend_id) values (1,4);
insert into tbl_user_friends (user_id, friend_id) values (1,5);
insert into tbl_user_friends (user_id, friend_id) values (1,6);
insert into tbl_user_friends (user_id, friend_id) values (1,7);
insert into tbl_user_friends (user_id, friend_id) values (1,8);
insert into tbl_user_friends (user_id, friend_id) values (2,1);
insert into tbl_user_friends (user_id, friend_id) values (2,3);
insert into tbl_user_friends (user_id, friend_id) values (2,4);
insert into tbl_user_friends (user_id, friend_id) values (2,5);
insert into tbl_user_friends (user_id, friend_id) values (2,6);
insert into tbl_user_friends (user_id, friend_id) values (2,7);
insert into tbl_user_friends (user_id, friend_id) values (2,8);
insert into tbl_user_friends (user_id, friend_id) values (3,1);
insert into tbl_user_friends (user_id, friend_id) values (3,2);
insert into tbl_user_friends (user_id, friend_id) values (4,1);
insert into tbl_user_friends (user_id, friend_id) values (4,2);
insert into tbl_user_friends (user_id, friend_id) values (5,1);
insert into tbl_user_friends (user_id, friend_id) values (5,2);
insert into tbl_user_friends (user_id, friend_id) values (6,1);
insert into tbl_user_friends (user_id, friend_id) values (6,2);
insert into tbl_user_friends (user_id, friend_id) values (7,1);
insert into tbl_user_friends (user_id, friend_id) values (7,2);
insert into tbl_user_friends (user_id, friend_id) values (8,1);
insert into tbl_user_friends (user_id, friend_id) values (8,2);

insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 1, 2, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 1, 3, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 1, 4, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 1, 5, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 1, 6, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 1, 7, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 1, 8, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 2, 1, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 2, 3, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 2, 4, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 2, 5, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 2, 6, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 2, 7, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 2, 8, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 3, 1, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 3, 2, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 4, 1, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 4, 2, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 5, 1, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 5, 2, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 6, 1, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 6, 2, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 7, 1, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 7, 2, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 8, 1, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tbl_user_subscription (id, user_id, subscribed_to, status, created_on, updated_on) values (NEXTVAL('hibernate_sequence'), 8, 2, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
